process.env.BABEL_ENV = 'development';
process.env.NODE_ENV = 'development';
console.log('before require env');
require('react-scripts/config/env');
console.log('after env');
const fs = require('fs');
const paths = require('react-scripts/config/paths');
console.log('paths loaded');
const checkRequiredFiles = require('react-dev-utils/checkRequiredFiles');
console.log('checkRequiredFiles loaded');
console.log('check files', checkRequiredFiles([paths.appHtml, paths.appIndexJs]));
const { choosePort, createCompiler, prepareProxy, prepareUrls } = require('react-dev-utils/WebpackDevServerUtils');
console.log('WebpackDevServerUtils loaded');
console.log('loading webpack');
const webpack = require('webpack');
console.log('webpack loaded');
console.log('loading webpack.config');
const configFactory = require('react-scripts/config/webpack.config');
console.log('webpack.config loaded');
console.log('loading WebpackDevServer');
const WebpackDevServer = require('webpack-dev-server');
console.log('WebpackDevServer loaded');
console.log('loading webpackDevServer.config');
const createDevServerConfig = require('react-scripts/config/webpackDevServer.config');
console.log('webpackDevServer.config loaded');
process.exit(0);
